## Entrenar Modelo con Tensor Flow

En este notebook usaremos una red neuronal para realizar el entranmiento, sin hacer la limpieza de los datos, como bien se realizo para el notebook train-mode.ipynb

In [1]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from tensorflow.keras import regularizers

2024-08-26 20:13:03.493346: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-26 20:13:03.509024: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-26 20:13:03.533373: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-26 20:13:03.533405: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-26 20:13:03.548339: I tensorflow/core/platform/cpu_feature_gua

Se cargan los datos

In [2]:
# Load data
data_file = "data.txt"
data = np.loadtxt(data_file)

Separamos las clases y las características

In [3]:
# Split data into features (X) and labels (y)
X = data[:, :-1]  # Features are all columns except the last one
y = data[:, -1]   # Labels are the last column

Separamos el conjunto de datos en train y test

In [4]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

Normalizamos los datos para pasarlo por la red neuronal

In [5]:
# Normalize the data (important for neural networks)
X_train = X_train / np.max(X_train)
X_test = X_test / np.max(X_test)

Convertimos variables categoricas a numericas usando one-hot encoding

In [6]:
# Convert labels to categorical (one-hot encoding)
y_train = tf.keras.utils.to_categorical(y_train, num_classes=3)  # Adjust num_classes as needed
y_test = tf.keras.utils.to_categorical(y_test, num_classes=3)

Configuramos una red neuronal convolucional CNN con una función de activación softmax en la ultima capa para las 3 clases

In [7]:
# Define a fully connected neural network (MLP)
model = tf.keras.Sequential([
    tf.keras.layers.Dense(256, activation='relu', input_shape=(X_train.shape[1],)),  # Más neuronas
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')  # Cambiar a 3 clases
])

2024-08-26 20:13:06.250327: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-08-26 20:13:06.300308: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-08-26 20:13:06.303351: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-

In [8]:
# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])


Realizamos el entrenamiento del modelo

In [9]:
# Train the model
model.fit(X_train, y_train, epochs=80, batch_size=32, validation_split=0.2)

Epoch 1/80


I0000 00:00:1724703198.901177    3076 service.cc:145] XLA service 0x7f8c78c07250 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1724703198.901214    3076 service.cc:153]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2024-08-26 20:13:18.907892: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-08-26 20:13:18.927069: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:465] Loaded cuDNN version 8907
I0000 00:00:1724703198.985390    3076 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


13/13 [==============================] - 13s 39ms/step - loss: 1.1364 - accuracy: 0.3375 - val_loss: 1.1287 - val_accuracy: 0.3200
Epoch 2/80
13/13 [==============================] - 0s 5ms/step - loss: 1.1112 - accuracy: 0.3098 - val_loss: 1.0898 - val_accuracy: 0.3200
Epoch 3/80
13/13 [==============================] - 0s 5ms/step - loss: 1.1046 - accuracy: 0.3375 - val_loss: 1.0907 - val_accuracy: 0.3200
Epoch 4/80
13/13 [==============================] - 0s 5ms/step - loss: 1.1021 - accuracy: 0.3577 - val_loss: 1.0918 - val_accuracy: 0.3500
Epoch 5/80
13/13 [==============================] - 0s 5ms/step - loss: 1.0854 - accuracy: 0.3577 - val_loss: 1.0770 - val_accuracy: 0.3400
Epoch 6/80
13/13 [==============================] - 0s 5ms/step - loss: 1.0923 - accuracy: 0.3426 - val_loss: 1.0695 - val_accuracy: 0.3500
Epoch 7/80
13/13 [==============================] - 0s 5ms/step - loss: 1.0655 - accuracy: 0.4710 - val_loss: 1.0499 - val_accuracy: 0.5300
Epoch 8/80
13/13 [===========

Realizamos la evaluación del modelo

In [10]:
# Evaluate the model on the test data
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(f"Test accuracy: {test_acc * 100:.2f}%")

4/4 - 0s - loss: 0.2589 - accuracy: 0.9040 - 29ms/epoch - 7ms/step
Test accuracy: 90.40%


Calculamos la matriz de confusión

In [11]:
# Confusion matrix
y_pred = np.argmax(model.predict(X_test), axis=1)
y_true = np.argmax(y_test, axis=1)
print(confusion_matrix(y_true, y_pred))

4/4 [==============================] - 0s 2ms/step
[[41  0  1]
 [ 0 40  1]
 [ 0 10 32]]


In [12]:
# Save the model
model.save('./dense_model')

INFO:tensorflow:Assets written to: ./dense_model/assets


INFO:tensorflow:Assets written to: ./dense_model/assets


## Inferencia

Cargamos el modelo

In [13]:
from tensorflow.keras.models import load_model

# Cargar el modelo guardado
model = load_model('./dense_model')

Usamos 3 items del dataset de evaluación

In [14]:
X_new = np.array([X_test[1],
                  X_test[20],  # Ejemplo de nuevo vector de características
                  X_test[-1]])

In [15]:
# Hacer predicciones
predictions = model.predict(X_new)

1/1 [==============================] - 0s 150ms/step


In [16]:
# Obtener la clase predicha
predicted_classes = np.argmax(predictions, axis=1)

Clases predichas

In [17]:
print(predicted_classes)

[0 1 2]
